# Uncomment your system
LINUX = 1
#MAC = 1

# Uncomment your window binding
#BINDING_NONE = 1
BINDING_GLUT = 1

# Customize to fit your system
PREFIX = /usr/local
CONFPREFIX = $(PREFIX)/etc
MANPREFIX = $(PREFIX)/share/man
LIBS = -L$(PREFIX)/lib -L/usr/lib
CFLAGS = -O3 -I. -I./include -I$(PREFIX)/include -I/usr/include
LDFLAGS = $(LIBS)
AR = ar cr
CC = g++
RANLIB = ranlib
BINDING_SRC = 

# OS dependent section
ifdef LINUX
	LDFLAGS += -lGLEW -lglut -lGLU -lGL
	CFLAGS += -DLINUX
endif
ifdef MAC
	LDFLAGS += -framework GLUT -framework AGL -framework OpenGL
endif

ifdef BINDING_GLUT
	BINDING_SRC = glv_binding_glut.cpp
endif

